name: Conda

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create Environment
      run: |
        conda create --name tms python=$PYTHON_VERSION
        conda init
    - name: Install dependencies
      run: |
        source /usr/share/miniconda/bin/activate
        conda activate tms
        pip install -r requirements.txt
    - name: Run tests1
      run: python --version
    - name: Run tests2
      run: gcc --version
